# Generated by Django 5.2.5 on 2025-08-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=255, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(verbose_name="Время на выполнение (в секундах)"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False, verbose_name="Признак приятной привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Место"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(max_length=255, verbose_name="Вознаграждение"),
        ),
    ]
