# Generated by Django 5.2.5 on 2025-08-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options_alter_habit_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="user",
        ),
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение"),
        ),
    ]
